const tableData=[
    {
        "poNumber":"PO123456",
        "appID":"app1",
        "status":"created",
        "deficit":"100",
        "assignedTo":"supplier1@boeing.com"
    },
    {
        "poNumber":"PO123457",
        "appID":"app2",
        "status":"pending",
        "deficit":"50",
        "assignedTo":"supplier1@boeing.com"
    },
    {
        "poNumber":"PO123458",
        "appID":"app3",
        "status":"pending",
        "deficit":"50",
        "assignedTo":"supplier1@boeing.com"
    },
    {
        "poNumber":"PO123458",
        "appID":"app4",
        "status":"pending",
        "deficit":"50",
        "assignedTo":"supplier1@boeing.com"
    },
    {
        "poNumber":"PO123474",
        "appID":"app5",
        "status":"pending",
        "deficit":"50",
        "assignedTo":"supplier1@boeing.com"
    },
    {
        "poNumber":"PO123453",
        "appID":"app6",
        "status":"pending",
        "deficit":"50",
        "assignedTo":"supplier1@boeing.com"
    }

]

    module.exports=tableData
